import type * as React from 'react'
import images from '~/data/images.gen.json'

export type ImageName = keyof typeof images

export function imageMeta(name: ImageName) {
  return images[name]
}

// Renders a WebP srcset generated by `bun run images` from images/originals.
export function ResponsiveImage({
  name,
  alt,
  sizes,
  className,
  style,
  priority = false,
}: {
  name: ImageName
  alt: string
  sizes: string
  className?: string
  style?: React.CSSProperties
  priority?: boolean
}) {
  const image = images[name]
  const src = (width: number) => `${name}-${width}.webp`
  const fallbackWidth = image.widths.find((w) => w >= 800) ?? image.width

  return (
    <img
      src={src(fallbackWidth)}
      srcSet={image.widths.map((w) => `${src(w)} ${w}w`).join(', ')}
      sizes={sizes}
      width={image.width}
      height={image.height}
      alt={alt}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : undefined}
      decoding={priority ? 'sync' : 'async'}
      className={className}
      style={style}
    />
  )
}
