/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaiereLaserPlexiglasRouteImport } from './routes/taiere-laser-plexiglas'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as PortofoliuRouteImport } from './routes/portofoliu'
import { Route as PlacuteAdresaRouteImport } from './routes/placute-adresa'
import { Route as LitereVolumetriceRouteImport } from './routes/litere-volumetrice'
import { Route as GravuraLaserCraiovaRouteImport } from './routes/gravura-laser-craiova'
import { Route as GloburiCraciunPersonalizateRouteImport } from './routes/globuri-craciun-personalizate'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CadouriPersonalizateRouteImport } from './routes/cadouri-personalizate'
import { Route as IndexRouteImport } from './routes/index'

const TaiereLaserPlexiglasRoute = TaiereLaserPlexiglasRouteImport.update({
  id: '/taiere-laser-plexiglas',
  path: '/taiere-laser-plexiglas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofoliuRoute = PortofoliuRouteImport.update({
  id: '/portofoliu',
  path: '/portofoliu',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacuteAdresaRoute = PlacuteAdresaRouteImport.update({
  id: '/placute-adresa',
  path: '/placute-adresa',
  getParentRoute: () => rootRouteImport,
} as any)
const LitereVolumetriceRoute = LitereVolumetriceRouteImport.update({
  id: '/litere-volumetrice',
  path: '/litere-volumetrice',
  getParentRoute: () => rootRouteImport,
} as any)
const GravuraLaserCraiovaRoute = GravuraLaserCraiovaRouteImport.update({
  id: '/gravura-laser-craiova',
  path: '/gravura-laser-craiova',
  getParentRoute: () => rootRouteImport,
} as any)
const GloburiCraciunPersonalizateRoute =
  GloburiCraciunPersonalizateRouteImport.update({
    id: '/globuri-craciun-personalizate',
    path: '/globuri-craciun-personalizate',
    getParentRoute: () => rootRouteImport,
  } as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CadouriPersonalizateRoute = CadouriPersonalizateRouteImport.update({
  id: '/cadouri-personalizate',
  path: '/cadouri-personalizate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadouri-personalizate': typeof CadouriPersonalizateRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/globuri-craciun-personalizate': typeof GloburiCraciunPersonalizateRoute
  '/gravura-laser-craiova': typeof GravuraLaserCraiovaRoute
  '/litere-volumetrice': typeof LitereVolumetriceRoute
  '/placute-adresa': typeof PlacuteAdresaRoute
  '/portofoliu': typeof PortofoliuRoute
  '/servicii': typeof ServiciiRoute
  '/taiere-laser-plexiglas': typeof TaiereLaserPlexiglasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadouri-personalizate': typeof CadouriPersonalizateRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/globuri-craciun-personalizate': typeof GloburiCraciunPersonalizateRoute
  '/gravura-laser-craiova': typeof GravuraLaserCraiovaRoute
  '/litere-volumetrice': typeof LitereVolumetriceRoute
  '/placute-adresa': typeof PlacuteAdresaRoute
  '/portofoliu': typeof PortofoliuRoute
  '/servicii': typeof ServiciiRoute
  '/taiere-laser-plexiglas': typeof TaiereLaserPlexiglasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadouri-personalizate': typeof CadouriPersonalizateRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/globuri-craciun-personalizate': typeof GloburiCraciunPersonalizateRoute
  '/gravura-laser-craiova': typeof GravuraLaserCraiovaRoute
  '/litere-volumetrice': typeof LitereVolumetriceRoute
  '/placute-adresa': typeof PlacuteAdresaRoute
  '/portofoliu': typeof PortofoliuRoute
  '/servicii': typeof ServiciiRoute
  '/taiere-laser-plexiglas': typeof TaiereLaserPlexiglasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadouri-personalizate'
    | '/contact'
    | '/despre-noi'
    | '/globuri-craciun-personalizate'
    | '/gravura-laser-craiova'
    | '/litere-volumetrice'
    | '/placute-adresa'
    | '/portofoliu'
    | '/servicii'
    | '/taiere-laser-plexiglas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadouri-personalizate'
    | '/contact'
    | '/despre-noi'
    | '/globuri-craciun-personalizate'
    | '/gravura-laser-craiova'
    | '/litere-volumetrice'
    | '/placute-adresa'
    | '/portofoliu'
    | '/servicii'
    | '/taiere-laser-plexiglas'
  id:
    | '__root__'
    | '/'
    | '/cadouri-personalizate'
    | '/contact'
    | '/despre-noi'
    | '/globuri-craciun-personalizate'
    | '/gravura-laser-craiova'
    | '/litere-volumetrice'
    | '/placute-adresa'
    | '/portofoliu'
    | '/servicii'
    | '/taiere-laser-plexiglas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadouriPersonalizateRoute: typeof CadouriPersonalizateRoute
  ContactRoute: typeof ContactRoute
  DespreNoiRoute: typeof DespreNoiRoute
  GloburiCraciunPersonalizateRoute: typeof GloburiCraciunPersonalizateRoute
  GravuraLaserCraiovaRoute: typeof GravuraLaserCraiovaRoute
  LitereVolumetriceRoute: typeof LitereVolumetriceRoute
  PlacuteAdresaRoute: typeof PlacuteAdresaRoute
  PortofoliuRoute: typeof PortofoliuRoute
  ServiciiRoute: typeof ServiciiRoute
  TaiereLaserPlexiglasRoute: typeof TaiereLaserPlexiglasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taiere-laser-plexiglas': {
      id: '/taiere-laser-plexiglas'
      path: '/taiere-laser-plexiglas'
      fullPath: '/taiere-laser-plexiglas'
      preLoaderRoute: typeof TaiereLaserPlexiglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofoliu': {
      id: '/portofoliu'
      path: '/portofoliu'
      fullPath: '/portofoliu'
      preLoaderRoute: typeof PortofoliuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placute-adresa': {
      id: '/placute-adresa'
      path: '/placute-adresa'
      fullPath: '/placute-adresa'
      preLoaderRoute: typeof PlacuteAdresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litere-volumetrice': {
      id: '/litere-volumetrice'
      path: '/litere-volumetrice'
      fullPath: '/litere-volumetrice'
      preLoaderRoute: typeof LitereVolumetriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gravura-laser-craiova': {
      id: '/gravura-laser-craiova'
      path: '/gravura-laser-craiova'
      fullPath: '/gravura-laser-craiova'
      preLoaderRoute: typeof GravuraLaserCraiovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globuri-craciun-personalizate': {
      id: '/globuri-craciun-personalizate'
      path: '/globuri-craciun-personalizate'
      fullPath: '/globuri-craciun-personalizate'
      preLoaderRoute: typeof GloburiCraciunPersonalizateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadouri-personalizate': {
      id: '/cadouri-personalizate'
      path: '/cadouri-personalizate'
      fullPath: '/cadouri-personalizate'
      preLoaderRoute: typeof CadouriPersonalizateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadouriPersonalizateRoute: CadouriPersonalizateRoute,
  ContactRoute: ContactRoute,
  DespreNoiRoute: DespreNoiRoute,
  GloburiCraciunPersonalizateRoute: GloburiCraciunPersonalizateRoute,
  GravuraLaserCraiovaRoute: GravuraLaserCraiovaRoute,
  LitereVolumetriceRoute: LitereVolumetriceRoute,
  PlacuteAdresaRoute: PlacuteAdresaRoute,
  PortofoliuRoute: PortofoliuRoute,
  ServiciiRoute: ServiciiRoute,
  TaiereLaserPlexiglasRoute: TaiereLaserPlexiglasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
